config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :task_new
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :task_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    # @class = if @task.completed
    #            'fa-regular fa-square'
    #          else
    #            'fa-regular fa-square-check'
    #          end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to :tasks, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>

  <%= form_with model: @task do |f| %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
      <% @task.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :details %><br>
      <%= f.text_area :details, class: "form-control" %>
      <% @task.errors.full_messages_for(:details).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <div>

    <div>
      <%= f.check_box :completed %>
      <%= f.label :completed, "Completed" %>
    </div>

    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <hr>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <ul class="list-unstyled" style="width: 300px">
    <% @tasks.each do |task| %>
      <li class="d-flex justify-content-between">
        <div>
          <% if task.completed %>
            <i class="fa-regular fa-square-check"></i>
          <% else %>
            <i class="fa-regular fa-square"></i>
          <% end %>
          <%= link_to task.title, task %>
          <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <hr>
  <%= link_to "Add a new task", :task_new %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create new task</h1>

  <%= form_with model: @task do |f| %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
      <% @task.errors.full_messages_for(:title).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= f.label :details %><br>
      <%= f.text_area :details, class: "form-control" %>
      <% @task.errors.full_messages_for(:details).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    <div>

    <%= f.submit class: "my-3 btn btn-primary" %>
  <% end %>
  <hr>
  <%= link_to "Back to tasks", :tasks %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="d-flex align-items-center justify-content-between">
    <h1><%= @task.title %></h1>
    <%= link_to task_edit_path(@task) do %>
      <i class="fa-solid fa-pencil"></i>
      Edit
    <% end %>
  </div>

  <div class="card p-4 bg-light">
    <p class="m-0"><%= @task.details %></p>
  </div>

  <p>
    <% if @task.completed %>
      <i class="fa-regular fa-square-check"></i>
      This task is completed
    <% else %>
      <i class="fa-regular fa-square"></i>
      This task is not completed yet
    <% end %>
  </p>
  <hr>
  <%= link_to "Back to tasks", tasks_path %>
</div>